--
-- Table structure for table game
--

CREATE TABLE games (
                      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      quantity integer DEFAULT NULL,
                      name varchar(255) DEFAULT NULL,
                      price numeric(38,2) DEFAULT NULL,
                      img_url varchar(255) DEFAULT NULL,
                      rating numeric(38,2) DEFAULT NULL,
                      description text NOT NULL,
                      tags varchar(255) NOT NULL DEFAULT ''
);

--
-- Dumping data for table game
--

INSERT INTO games (id, quantity, name, price, img_url, rating, description, tags) VALUES
                                                                                               (1, 88, 'Dragon Ball Xenoverse 2', 35.66, '/imgs/xeno2.jpg', 7.00, 'The story continues from the first Xenoverse game. After the events of the original, the hero of that game is celebrated as a legend while continuing their time-protecting mission. However, in this installment, you play as a new character who is just starting their journey as a Time Patroller.', 'Fighting, RPG, Adventure'),
                                                                                               (2, 50, 'Call of Duty: Black Ops', 35.99, '/imgs/bo.jpg', 8.50, 'A FPS bestseller developed by Treyarch. Spectacular set pieces, an engaging narrative, and impressive visual effects are integral parts of the Black Ops experience.', 'Action, Horror, Shooter'),
                                                                                               (3, 90, 'Dark Souls 3', 66.85, '/imgs/ds3.jpg', 8.00, 'The Dark Souls series was created by the Japanese studio FromSoftware Inc. The game transports players to the dark world of Lothric. Choose from 12 character classes (including Knight, Mercenary, Herald, Warrior), each offering distinct attributes and equipment.', 'RPG, Adventure, Fantasy'),
                                                                                               (4, 106, 'Elden Ring', 249.99, '/imgs/elden.jpg', 8.50, 'A dark fantasy action-RPG developed by FromSoftware. It is a challenging adventure created by the developers of Demon Souls in collaboration with George R.R. Martin, author of A Song of Ice and Fire. Uncover the secrets of the Lands Between and fulfill your destiny.', 'RPG, Adventure, Fantasy'),
                                                                                               (5, 67, 'FIFA 21', 84.00, '/imgs/fifa21.jpg', 6.50, 'A football sports game developed by EA Vancouver and published by EA Sports. FIFA 21 is another installment in the iconic football series dating back to the late 1990s. Take control of your favorite team and compete against players online or vs CPU offline.', 'Sports'),
                                                                                               (6, 94, 'God of War', 80.00, '/imgs/gow.jpg', 9.00, 'An action-RPG developed by Santa Monica Studio. After completing his vengeful quest in Greece, Kratos ventures to the Norse realm to face mythological beasts and gods once again. This time, however, he will not be traveling alone.', 'RPG, Adventure, Fantasy, Action'),
                                                                                               (7, 73, 'God of War Ragnarok', 249.99, '/imgs/gowr.jpg', 9.50, 'An action game released in 2022 by Santa Monica Studio, serving as the sequel to God of War (2018). It follows Kratos and his son Atreus as they face the onset of Ragnarok, the apocalyptic end predicted in Norse mythology.', 'RPG, Adventure, Fantasy, Action'),
                                                                                               (8, 48, 'Call of Duty: Modern Warfare 2', 77.00, '/imgs/mw2.jpg', 8.50, 'The sequel to the record-breaking FPS bestseller, Modern Warfare 2 features new gripping missions as a grave new threat brings the world to the brink of collapse.', 'Action, Shooter'),
                                                                                               (9, 88, 'Call of Duty: Modern Warfare 3', 84.55, '/imgs/mw3.jpg', 8.00, 'A first-person shooter published by Activision and developed by Infinity Ward, Sledgehammer Games, and Raven Software. It serves as the third entry in the Modern Warfare series and a direct continuation of 2009''s Call of Duty: Modern Warfare 2.', 'Action, Shooter'),
                                                                                               (10, 156, 'Red Dead Redemption 2', 119.99, '/imgs/rdr2.jpg', 10.00, 'An action-adventure game released for Xbox One and PlayStation 4 in 2018, and PC in 2019. Serving as a prequel to 2010''s Red Dead Redemption, it follows outlaw Arthur Morgan. Immerse yourself in a vast open world filled with incredible interactions, activities, and stunning visual fidelity.', 'Action, Shooter, Adventure'),
                                                                                               (11, 204, 'Dragon Ball Sparking Zero', 339.00, '/imgs/spar.jpg', 8.50, 'An anime-style fighting game serving as a new entry in the Dragon Ball Z: Budokai Tenkaichi series. Developed by Spike Chunsoft Co., Ltd. and published by Bandai Namco Entertainment. Building on the success of the original trilogy, it lets players engage in high-octane 3D arena battles.', 'Action, Fighting'),
                                                                                               (12, 110, 'The Witcher 3: Wild Hunt', 56.00, '/imgs/w3.jpg', 10.00, 'An open-world action-RPG where players control Geralt of Rivia from a third-person perspective, with certain story segments featuring Ciri. Traverse expansive lands or explore underwater through swimming and diving mechanics.', 'Fantasy, RPG, Action, Adventure'),
                                                                                               (13, 36, 'Hogwarts Legacy', 80.00, '/imgs/hog.jpg', 7.50, 'An immersive open-world action-RPG set in the universe first introduced in the Harry Potter books. Embark on a journey through familiar and new locations, discover fantastic beasts, customize your character, and craft potions.', 'Fantasy, RPG, Action, Adventure'),
                                                                                               (14, 27, 'Dragon Ball Z: Kakarot', 63.63, '/imgs/hog.jpg', 8.50, 'An action-RPG developed by CyberConnect2 and published in 2020 by Bandai Namco Entertainment. Follow the legendary story of Son Goku (Kakarot) across iconic sagas from the original manga, crafted to recreate Akira Toriyama''s universe as faithfully as possible.', 'RPG, Action, Adventure'),
                                                                                               (15, 140, 'Crash Bandicoot 4', 134.44, '/imgs/crash.jpg', 8.50, 'A 3D platformer developed by Toys for Bob that acts as the direct sequel to 2007''s Crash Bandicoot 3: Warped. Explore colorful worlds, leap across obstacles, avoid traps, and defeat enemies.', 'Platformer, Action, Adventure'),
                                                                                               (16, 66, 'Ghost of Tsushima', 339.00, '/imgs/ghost.jpg', 9.00, 'An open-world action game set in feudal Japan. Play as Jin Sakai, a samurai who must risk everything to defend Tsushima Island from a Mongol invasion.', 'Action, Adventure');

SELECT setval(pg_get_serial_sequence('games', 'id'), coalesce(max(id), 1)) FROM games;

--
-- Table structure for table users
--

CREATE TABLE users (
                       id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username varchar(255) DEFAULT NULL,
                       password varchar(255) NOT NULL,
                       role varchar(255) DEFAULT NULL
);

--
-- Dumping data for table users
--

INSERT INTO users (id, username, password, role) VALUES
                                                     (1, 'admin', 'haslo', 'admin'),
                                                     (2, 'user', 'haslo', 'user'),
                                                     (3, 'user2', 'haslo', 'user');

SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id), 1)) FROM users;

--
-- Table structure for table orders
--

CREATE TABLE orders (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id integer NOT NULL,
                        order_date timestamp DEFAULT CURRENT_TIMESTAMP,
                        total_price numeric(10,2) NOT NULL,
                        CONSTRAINT orders_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_orders_user_id ON orders (user_id);

--
-- Dumping data for table orders
--

INSERT INTO orders (id, user_id, order_date, total_price) VALUES
                                                              (1, 2, '2025-11-04 22:10:01', 249.94),
                                                              (7, 3, '2025-11-05 12:50:01', 205.35),
                                                              (8, 2, '2025-11-05 15:18:06', 571.63);

SELECT setval(pg_get_serial_sequence('orders', 'id'), coalesce(max(id), 1)) FROM orders;

--
-- Table structure for table order_items
--

CREATE TABLE order_items (
                             id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id integer NOT NULL,
                             game_id integer NOT NULL,
                             quantity integer NOT NULL,
                             unit_price numeric(38,2) DEFAULT NULL,
                             name varchar(255) DEFAULT NULL,
                             CONSTRAINT order_items_ibfk_1 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
                             CONSTRAINT order_items_ibfk_2 FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_game_id ON order_items (game_id);

--
-- Dumping data for table order_items
--

INSERT INTO order_items (id, order_id, game_id, quantity, unit_price, name) VALUES
                                                                                (1, 1, 1, 2, 59.99, NULL),
                                                                                (2, 1, 3, 1, 39.99, NULL),
                                                                                (3, 1, 5, 3, 29.99, NULL),
                                                                                (4, 7, 1, 1, 35.66, NULL),
                                                                                (5, 7, 2, 1, 35.99, NULL),
                                                                                (6, 7, 3, 2, 66.85, NULL),
                                                                                (7, 8, 1, 1, 35.66, NULL),
                                                                                (8, 8, 2, 1, 35.99, NULL),
                                                                                (9, 8, 4, 2, 249.99, NULL);

SELECT setval(pg_get_serial_sequence('order_items', 'id'), coalesce(max(id), 1)) FROM order_items;